version: '3'
services:
  bot:
    build: .
    command: python3 bot.py
    volumes:
      - .:/code
  api:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/code
    ports:
      - 8000:8000
